name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - src/main_functions.py
      - tests/test_main_functions.py
  pull_request:
    branches:
      - main
      - src/main_functions.py
      - tests/test_main_functions.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: List directory contents
        run: ls -R

      - name: Run tests with pytest
        run: |
          python -m pytest tests/test_main_functions.py --maxfail=1 --disable-warnings -v
        env:
          PYTHONPATH: ${{ github.workspace }}/src
