name: Continuous Integration (CI)

on:
  push:
    branches:
      - main                       # Trigger on push to 'main' branch
      - main_functions.py
      - tests/test_main_functions.py
  pull_request:
    branches:
      - main                       # Trigger on pull requests to 'main' branch
      - main_functions.py
      - tests/test_main_functions.py

jobs:
  build:
    runs-on: ubuntu-latest        # Use GitHub's hosted Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'     # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          python -m pip install -r src/requirements.txt  # Install dependencies from requirements.txt

      - name: List directory contents          # Add this step for debugging
        run: ls -R                             # List all files and directories recursively

      - name: Check if test directory exists    # Check specifically for test folder
        run: |
          echo "Current working directory:"
          pwd                                    # Print the current working directory
          echo "Listing contents:"
          ls -la                                 # List all files and directories in the current directory
          if [ ! -d test ]; then echo "Directory 'test' does not exist."; exit 1; fi

      - name: Run tests with pytest
        run: |
          python -m pytest test/ --maxfail=1 --disable-warnings -v  # Run all tests in the 'test' directory
        env:
          PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}