name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - src/main_functions.py
      - tests/test_main_functions.py
  pull_request:
    branches:
      - main
      - src/main_functions.py
      - tests/test_main_functions.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: List directory contents
        run: ls -R

      - name: Run tests
        run: |
          if [ -f test/test_main_functions.py ]; then
            python -m pytest test/test_main_functions.py --maxfail=1 --disable-warnings -v
          elif [ -f tests/test_main_functions.py ]; then
            python -m pytest tests/test_main_functions.py --maxfail=1 --disable-warnings -v
          else
            echo "Error: test_main_functions.py not found in test/ or tests/ directory"
            exit 1
          fi
        env:
          PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}